# Generated by Django 5.0.6 on 2024-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
