# Generated by Django 5.0.6 on 2024-05-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_confirmation',
        ),
    ]
