# Generated by Django 5.0.6 on 2024-05-22 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_journal', '0005_delete_requirements_alter_paper_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirements_parts_uz', models.CharField(max_length=100)),
                ('requirements_parts_en', models.CharField(max_length=100)),
                ('requirements_title_uz', models.TextField()),
                ('requirements_title_en', models.TextField()),
                ('requirements_description_uz', models.TextField()),
                ('requirements_description_en', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_journal.paper')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'db_table': 'requirements',
            },
        ),
    ]
