# Generated by Django 5.0.6 on 2024-05-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0005_delete_requirements_alter_paper_user'),
        ('app_main', '0002_remove_requirements_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_journal.paper'),
            preserve_default=False,
        ),
    ]
