# Generated by Django 5.0.6 on 2024-05-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_logo', models.ImageField(null=True, upload_to='images_journal/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('number_views', models.IntegerField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('file', models.FileField(null=True, upload_to='media/files_journal/')),
            ],
            options={
                'verbose_name_plural': 'Papers',
                'db_table': 'paper',
            },
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='requirements',
            table='requirements',
        ),
        migrations.CreateModel(
            name='PaperMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('edition_logo', models.ImageField(null=True, upload_to='images_journal/')),
                ('description', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_journal.journalmain')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name_uz', models.CharField(max_length=250)),
                ('journal_name_en', models.CharField(max_length=250)),
                ('journal_description_uz', models.CharField(max_length=500)),
                ('journal_description_en', models.CharField(max_length=500)),
                ('journal_file', models.FileField(null=True, upload_to='media/files_journal/')),
                ('journal_avatar', models.ImageField(upload_to='media/images_files/')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='app_journal.paper')),
            ],
            options={
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
            },
        ),
    ]
