# Generated by Django 5.0.6 on 2024-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0002_journalmain_paper_remove_contacts_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='references',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
