# Generated by Django 5.0.6 on 2024-05-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0003_paper_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_journal.contacts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalmain',
            name='edition_logo',
            field=models.ImageField(default=1, upload_to='images_journal/'),
            preserve_default=False,
        ),
    ]
