# Generated by Django 5.0.6 on 2024-05-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0005_requirements_connection_alter_paper_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='connection',
        ),
    ]
